apiVersion: v1
kind: Pod
metadata:
  name: data-billy
  labels:
    app: hhh
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
    command: 
      - "/bin/bash"
      - "-c"
      - >
        cd /phys239-vol/phys139-239_final_project/src/data &&
        python root2hdf5.py
    resources:
      limits:
        memory: 32Gi
        cpu: "16"
      requests:
        memory: 32Gi
        cpu: "16"
    volumeMounts:
    - mountPath: /phys239-vol
      name: phys239-vol
  volumes:
    - name: phys239-vol
      persistentVolumeClaim:
        claimName: phys239-vol
  restartPolicy: Never
